// <auto-generated />
using System;
using System.Collections.Generic;
using LostColonyManager.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LostColonyManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260109071217_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LostColonyManager.Domain.Models.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<Guid>>("EventsIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("campaigns", (string)null);
                });

            modelBuilder.Entity("LostColonyManager.Domain.Models.Choice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("BonusType")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<Guid>>("ConsequencesIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("Name");

                    b.ToTable("choices", (string)null);
                });

            modelBuilder.Entity("LostColonyManager.Domain.Models.Consequence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChoiceId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxRange")
                        .HasColumnType("integer");

                    b.Property<int>("MinRange")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Target")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ChoiceId");

                    b.HasIndex("Name");

                    b.ToTable("consequences", (string)null);
                });

            modelBuilder.Entity("LostColonyManager.Domain.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<Guid>>("ChoicesIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ReferenceId");

                    b.HasIndex("Type");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("LostColonyManager.Domain.Models.Planet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<Guid>>("EventsIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Name");

                    b.ToTable("planets", (string)null);
                });

            modelBuilder.Entity("LostColonyManager.Domain.Models.Race", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<Guid>>("EventsIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Traits", "LostColonyManager.Domain.Models.Race.Traits#RaceTraits", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Culture")
                                .HasColumnType("integer")
                                .HasColumnName("traits_culture");

                            b1.Property<int>("Diplomacy")
                                .HasColumnType("integer")
                                .HasColumnName("traits_diplomacy");

                            b1.Property<int>("Power")
                                .HasColumnType("integer")
                                .HasColumnName("traits_power");

                            b1.Property<int>("Technology")
                                .HasColumnType("integer")
                                .HasColumnName("traits_technology");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("races", (string)null);
                });

            modelBuilder.Entity("LostColonyManager.Domain.Models.Structure", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("BonusType")
                        .HasColumnType("integer");

                    b.Property<string>("Cost")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Requeriments")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ReferenceId");

                    b.HasIndex("Type");

                    b.ToTable("structures", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
