// <auto-generated />
using System;
using System.Collections.Generic;
using LostColonyManager.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LostColonyManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260125010656_AddBonusTargetAndIncreasePerTurnToStructure")]
    partial class AddBonusTargetAndIncreasePerTurnToStructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LostColonyManager.Domain.Models.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("campaigns", (string)null);
                });

            modelBuilder.Entity("LostColonyManager.Domain.Models.Choice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("BonusType")
                        .HasColumnType("integer");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("Name");

                    b.ToTable("choices", (string)null);
                });

            modelBuilder.Entity("LostColonyManager.Domain.Models.Consequence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChoiceId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxRange")
                        .HasColumnType("integer");

                    b.Property<int>("MinRange")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Target")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ChoiceId");

                    b.HasIndex("Name");

                    b.ToTable("consequences", (string)null);
                });

            modelBuilder.Entity("LostColonyManager.Domain.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("PlanetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RaceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("Name");

                    b.HasIndex("PlanetId");

                    b.HasIndex("RaceId");

                    b.HasIndex("Type");

                    b.ToTable("events", null, t =>
                        {
                            t.HasCheckConstraint("CK_events_exactly_one_owner", "(CASE WHEN \"CampaignId\" IS NULL THEN 0 ELSE 1 END\r\n                     + CASE WHEN \"RaceId\"     IS NULL THEN 0 ELSE 1 END\r\n                     + CASE WHEN \"PlanetId\"   IS NULL THEN 0 ELSE 1 END) = 1");
                        });
                });

            modelBuilder.Entity("LostColonyManager.Domain.Models.Planet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Name");

                    b.ToTable("planets", (string)null);
                });

            modelBuilder.Entity("LostColonyManager.Domain.Models.Race", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Traits", "LostColonyManager.Domain.Models.Race.Traits#RaceTraits", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Culture")
                                .HasColumnType("integer")
                                .HasColumnName("traits_culture");

                            b1.Property<int>("Diplomacy")
                                .HasColumnType("integer")
                                .HasColumnName("traits_diplomacy");

                            b1.Property<int>("Power")
                                .HasColumnType("integer")
                                .HasColumnName("traits_power");

                            b1.Property<int>("Technology")
                                .HasColumnType("integer")
                                .HasColumnName("traits_technology");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("races", (string)null);
                });

            modelBuilder.Entity("PlanetStructure", b =>
                {
                    b.Property<Guid>("PlanetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StructureId")
                        .HasColumnType("uuid");

                    b.HasKey("PlanetId", "StructureId");

                    b.HasIndex("PlanetId");

                    b.HasIndex("StructureId");

                    b.ToTable("planet_structures", (string)null);
                });

            modelBuilder.Entity("Structure", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<int[]>("BonusTargets")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("BonusType")
                        .HasColumnType("integer");

                    b.Property<string>("Cost")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IncreasePerTurn")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Requeriments")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Type");

                    b.ToTable("structures", (string)null);
                });

            modelBuilder.Entity("LostColonyManager.Domain.Models.Choice", b =>
                {
                    b.HasOne("LostColonyManager.Domain.Models.Event", "Event")
                        .WithMany("Choices")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("LostColonyManager.Domain.Models.Consequence", b =>
                {
                    b.HasOne("LostColonyManager.Domain.Models.Choice", "Choice")
                        .WithMany("Consequences")
                        .HasForeignKey("ChoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Choice");
                });

            modelBuilder.Entity("LostColonyManager.Domain.Models.Event", b =>
                {
                    b.HasOne("LostColonyManager.Domain.Models.Campaign", "Campaign")
                        .WithMany("Events")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LostColonyManager.Domain.Models.Planet", "Planet")
                        .WithMany("Events")
                        .HasForeignKey("PlanetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LostColonyManager.Domain.Models.Race", "Race")
                        .WithMany("Events")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Campaign");

                    b.Navigation("Planet");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("PlanetStructure", b =>
                {
                    b.HasOne("LostColonyManager.Domain.Models.Planet", "Planet")
                        .WithMany("Structures")
                        .HasForeignKey("PlanetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Structure", "Structure")
                        .WithMany("Planets")
                        .HasForeignKey("StructureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planet");

                    b.Navigation("Structure");
                });

            modelBuilder.Entity("LostColonyManager.Domain.Models.Campaign", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("LostColonyManager.Domain.Models.Choice", b =>
                {
                    b.Navigation("Consequences");
                });

            modelBuilder.Entity("LostColonyManager.Domain.Models.Event", b =>
                {
                    b.Navigation("Choices");
                });

            modelBuilder.Entity("LostColonyManager.Domain.Models.Planet", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Structures");
                });

            modelBuilder.Entity("LostColonyManager.Domain.Models.Race", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Structure", b =>
                {
                    b.Navigation("Planets");
                });
#pragma warning restore 612, 618
        }
    }
}
